const GET_GAMES = 'GET_GAMES';
const GET_GAMES_SUCCESS = 'GET_GAMES_SUCCESS';
const GET_GAMES_FAILURE = 'GET_GAMES_FAILURE';
const SET_SEARCH_BAR = 'SET_SEARCH_BAR';

export { GET_GAMES, GET_GAMES_SUCCESS, GET_GAMES_FAILURE, SET_SEARCH_BAR };
